In [1]:
import pandas as pd
import numpy as np
w1 = [[3,1],[3,-1],[6,1],[6,-1]]
w2 = [[1,0],[0,1],[0,-1],[-1,0]]
w = [[3,1,0],[3,-1,0],[6,1,0],[6,-1,0],[1,0,1],[0,1,1],[0,-1,1],[-1,0,1]]
df = pd.DataFrame(w, columns=['X1','X2','Class'])
df

X1  X2  Class
0   3   1      0
1   3  -1      0
2   6   1      0
3   6  -1      0
4   1   0      1
5   0   1      1
6   0  -1      1
7  -1   0      1

In [2]:
n = len(df['X1'])
n

8

In [3]:
A = [[] for i in range(n)]
for i in range(n):
  A[i].append(1)
  A[i].append(df['X1'][i])
  A[i].append(df['X2'][i])

In [4]:
B = np.matrix(A)
B

matrix([[ 1,  3,  1],
        [ 1,  3, -1],
        [ 1,  6,  1],
        [ 1,  6, -1],
        [ 1,  1,  0],
        [ 1,  0,  1],
        [ 1,  0, -1],
        [ 1, -1,  0]])

In [5]:
C = np.linalg.inv(B.transpose()*B)*B.transpose()

In [6]:
C

matrix([[ 0.09223301,  0.09223301, -0.03883495, -0.03883495,  0.17961165,
          0.22330097,  0.22330097,  0.26699029],
        [ 0.01456311,  0.01456311,  0.07281553,  0.07281553, -0.02427184,
         -0.04368932, -0.04368932, -0.0631068 ],
        [ 0.16666667, -0.16666667,  0.16666667, -0.16666667,  0.        ,
          0.16666667, -0.16666667,  0.        ]])

In [7]:
Y = np.matrix(df['Class'])
Y
W = C * Y.transpose()

In [8]:
W

matrix([[ 0.89320388],
        [-0.17475728],
        [ 0.        ]])

In [64]:
from sklearn.linear_model import LinearRegression
X = df[['X1','X2']]
y = df['Class']
reg = LinearRegression().fit(X,y)
reg.score(X, y)
reg.coef_
# reg.predict(np.array([[3, 5]]))

array([-1.74757282e-01, -1.35973996e-16])

In [25]:
p = np.array(W)
p

array([[ 0.89320388],
       [-0.17475728],
       [ 0.        ]])

In [63]:
w0 = p[0][0]
w1 = [p[1][0],p[2][0]]
print(w0)
w1

0.8932038834951458


[-0.1747572815533981, 0.0]

In [68]:
def output(x):
  y = np.matrix(w1) *np.matrix(x).transpose() + w0
  if (y>=0.5):
    print(1)
  else:
    print(0)
  return y

In [78]:
output([3,5])


0


matrix([[0.36893204]])

In [50]:
y

matrix([[0.36893204]])

In [48]:
np.matrix(w1)


matrix([[-0.17475728,  0.        ]])

In [47]:
np.matrix([3,5]).shape

(1, 2)

In [41]:
np.matrix(w1).transpose() *np.matrix([3,5])

matrix([[-0.52427184, -0.87378641],
        [ 0.        ,  0.        ]])