**Dataset diabetes.csv consists of many features which generates the outcome as "1" and "0" ,denoting whether a person has diabetes or not respectively.Now given the dataset build a classification model using pseudo inverse such that if a new sample/data is provided to the model it classifies into "1" and "0", indicating whether a person has diabetes or not**

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df1 = df.drop(['Outcome'],axis=1)
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
A = [[] for i in range(len(df1))]
for i in range(len(df1)):
  A[i].append(1)
  A[i].append(df1['Pregnancies'][i])
  A[i].append(df1['Glucose'][i])
  A[i].append(df1['BloodPressure'][i])
  A[i].append(df1['SkinThickness'][i])
  A[i].append(df1['Insulin'][i])
  A[i].append(df1['BMI'][i])
  A[i].append(df1['DiabetesPedigreeFunction'][i])
  A[i].append(df1['Age'][i])

In [ ]:
B = np.matrix(A)
B

matrix([[  1.   ,   6.   , 148.   , ...,  33.6  ,   0.627,  50.   ],
        [  1.   ,   1.   ,  85.   , ...,  26.6  ,   0.351,  31.   ],
        [  1.   ,   8.   , 183.   , ...,  23.3  ,   0.672,  32.   ],
        ...,
        [  1.   ,   5.   , 121.   , ...,  26.2  ,   0.245,  30.   ],
        [  1.   ,   1.   , 126.   , ...,  30.1  ,   0.349,  47.   ],
        [  1.   ,   1.   ,  93.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
C = np.linalg.inv(B.transpose()*B)*B.transpose()

In [ ]:
Y = np.matrix(df['Outcome'])
Y
W = C * Y.transpose()

In [ ]:
W

matrix([[-8.53894266e-01],
        [ 2.05918715e-02],
        [ 5.92027295e-03],
        [-2.33187900e-03],
        [ 1.54519792e-04],
        [-1.80534514e-04],
        [ 1.32440315e-02],
        [ 1.47237439e-01],
        [ 2.62139380e-03]])

In [ ]:
#Checking values for Linear Regression
from sklearn.linear_model import LinearRegression
X = df1
y = df['Outcome']
reg = LinearRegression().fit(X,y)
reg.score(X, y)
print(reg.coef_)
print(reg.intercept_)
# reg.predict(np.array([[3, 5]]))

[ 0.02059187  0.00592027 -0.00233188  0.00015452 -0.00018053  0.01324403
  0.14723744  0.00262139]
-0.8538942664855473


In [ ]:
p = np.array(W)
p

array([[-8.53894266e-01],
       [ 2.05918715e-02],
       [ 5.92027295e-03],
       [-2.33187900e-03],
       [ 1.54519792e-04],
       [-1.80534514e-04],
       [ 1.32440315e-02],
       [ 1.47237439e-01],
       [ 2.62139380e-03]])

In [ ]:
w0 = p[0][0]
w1 = []
for i in range(1,len(p)):
  w1.append(p[i][0])
print(w0)
w1

-0.853894266485546


[0.020591871520332428,
 0.005920272947659845,
 -0.0023318790024440166,
 0.0001545197919451909,
 -0.00018053451356796576,
 0.013244031483241837,
 0.14723743863275254,
 0.002621393798269254]

In [ ]:
def output(x):
  y = np.matrix(w1) *np.matrix(x).transpose() + w0
  if (y>=0.5):
    # print(1)
    return 1
  else:
    # print(0)
    return 0

In [ ]:

x = [  1.   , 126.   ,  60.   ,   0.   ,   0.   ,  30.1  ,
           0.349,  47.    	]
output(x)

0

In [ ]:
actual_y = list(df['Outcome'])

In [ ]:
data = df1.to_numpy()

In [ ]:
predicted_y = []
for i in range(len(data)):
  predicted_y.append(output(data[i]))



In [ ]:
len(predicted_y)

768

In [ ]:
len(actual_y)
print(actual_y[0],predicted_y[0])

1 1


In [ ]:
count = 0
for i in range(len(actual_y)):
  if(actual_y[i] == predicted_y[i]):
    count = count + 1;
print(count)
accuracy = count/len(actual_y) * 100

602


In [ ]:
accuracy

78.38541666666666